version: "3.7"
services:
  app: #任意の名前を付ける。
    image: dpage/pgadmin4
    env_file:
      - environment.env
    deploy:
      resources: #リソースの制限
        limits: #CPU,メモリの上限設定
          cpus: '1.-0'
          memory: 100M
        reservations: #CPU,メモリの上限設定
          cpus: '0.25'
          memory: 25M
    #大量にログをはくコンテナだと、平気で30Gとか使ってくるから許容できる範囲を計算する
    logging:
      driver: json-file #json-file(default),syslog,none
      options:
        max-file: "10"
        max-size: "200k"
    networks: 
      - pgadmin4-nw
    ports:
      - 10080:80 #host:container
networks:
  pgadmin4-nw: #ネットワークの名前を指定
    external: false